/* tslint:disable */
/* eslint-disable */
/**
 * MindWalk 프로젝트 API 문서
 * MindWalk 프로젝트 API 문서입니다.
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthRequest
 */
export interface AuthRequest {
    /**
     * 
     * @type {number}
     * @memberof AuthRequest
     */
    oauthId: number;
}

/**
 * Check if a given object implements the AuthRequest interface.
 */
export function instanceOfAuthRequest(value: object): value is AuthRequest {
    if (!('oauthId' in value) || value['oauthId'] === undefined) return false;
    return true;
}

export function AuthRequestFromJSON(json: any): AuthRequest {
    return AuthRequestFromJSONTyped(json, false);
}

export function AuthRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'oauthId': json['oauthId'],
    };
}

export function AuthRequestToJSON(json: any): AuthRequest {
    return AuthRequestToJSONTyped(json, false);
}

export function AuthRequestToJSONTyped(value?: AuthRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'oauthId': value['oauthId'],
    };
}

